[tools]
# global tool versions go here
# you can set these with `mise use -g`
node = 'lts'
python = "latest"


[settings]
env_file = '.env'
# configure messages displayed when entering directories with config files
status = { missing_tools = "if_other_versions_installed", show_env = true, show_tools = true }
