[theme]
theme = "srcery"

[icons]
icons = "awesome6"

[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = " $icon $available "
format_alt = " $icon $available / $total "

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:M)/$swap_total.eng(w:3,u:B,p:M)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "cpu"
interval = 1
format_alt = " $icon $utilization "

[[block]]
block = "nvidia_gpu"
interval = 1
format = " $icon RTX 3070 $utilization $temperature $clocks "

[[block]]
block = "pacman"
interval = 600
format = " $icon $pacman updates available "
format_singular = " $icon $pacman update available "
format_up_to_date = " $icon system up to date "
critical_updates_regex = "(linux|linux-lts|linux-zen)"

[[block]]
block = "sound"
format = " $output_name{ $volume|} "
[block.mappings]
"alsa_output.pci-0000_00_1f.3.iec958-stereo" = "🔈"
"alsa_output.pci-0000_00_1b.0.analog-stereo" = "🎧"

[[block]]
block = "hueshift"
hue_shifter = "redshift"
step = 50
click_temp = 3500

[[block]]
block = "time"
interval = 60
[block.format]
full = "$icon $timestamp.datetime(f:'%a %Y-%m-%d %R') "
