[theme]
theme = "srcery"

[icons]
icons = "awesome6"


[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
path = "/home/"
alert = 10.0
warning = 15.0
format = " $icon $available "
format_alt = " $icon $available / $total "

[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = " $icon $available "
format_alt = " $icon $available / $total "

[[block]]
block = "memory"
format = " [ $icon $mem_used_percents.eng(w:1) ] "
format_alt = " [ $icon_swap $swap_free.eng(w:3,u:B,p:M)/$swap_total.eng(w:3,u:B,p:M)($swap_used_percents.eng(w:2)) ] "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "cpu"
interval = 1
format = " [ $icon $utilization ] "


[[block]]
block = "nvidia_gpu"
interval = 1
format = " [ $icon RTX 3070 $utilization $temperature $clocks ] "
# [[block.click]]
# button = "left"
# cmd = ""
# format = " $icon RTX 3070 $utilization"

[[block]]
block = "pacman"
interval = 600
format = " $icon $pacman updates available "
format_singular = " $icon $pacman update available "
format_up_to_date = " $icon system up to date "
critical_updates_regex = "(linux|linux-lts|linux-zen)"
# aur_command = "paru -Qua"
[[block.click]]
# pop-up a menu showing the available updates. Replace wofi with your favourite menu command.
button = "left"
cmd = "fakeroot pacman -Qu --dbpath /tmp/checkup-db-i3statusrs/ | rofi -dmenu"
[[block.click]]
# Updates the block on right click
button = "right"
update = true

[[block]]
block = "sound"
format = " $output_name{ $volume|} "
[block.mappings]
"alsa_output.pci-0000_00_1f.3.iec958-stereo" = "🔈"
"bluez_sink.5C_44_3E_31_44_6C.a2dp_sink" = "🎧"
# "alsa_output.pci-0000_00_1b.0.analog-stereo" = "🎧"

[[block]]
block = "hueshift"
hue_shifter = "redshift"
step = 50
click_temp = 3500

[[block]]
block = "net"
format = " $icon {$signal_strength} "

[[block]]
block = "time"
interval = 60
[block.format]
full = "$icon $timestamp.datetime(f:'%a %Y-%m-%d %R') "
short = " $icon $timestamp.datetime(f:%R) "
