# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

#my right format
right_format = "$time"


[time]
disabled = false
format = '[\[ $time \]]($style) '
time_format = "%d-%m-%Y  %T"
utc_time_offset = "local"


